name: Deploy CMS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Action for Sanity.io
        uses: sanity-io/github-action-sanity@v0.1-alpha
